### ISSUE TITLE
todo - projekt 2

### ISSUE THREAD

**Issue by martin-raden** [Dr-Eberle-Zentrum/DataBASHing#4]
- [x] CSV ausgabebeispiel
- [x] Beispiele für Staatenteile + Hinweise bzgl. führender Leerzeichen
- [x] CSV Zielzeilenzahl im Text für Abgleich

**Comment by martin-raden** [comment]
- [x] info, dass hochgeladene Dateien in ILIAS automatisch umbenannt werden (in .sec) = kein Problem
